-- ============================================================
-- Eternum - Cementerio Virtual
-- Database: eternum_db
-- PostgreSQL Script con estándares organizacionales
-- ============================================================

-- Crear base de datos
CREATE DATABASE eternum_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- Conectar a la base de datos
\c eternum_db;

-- Habilitar extensión pgcrypto para encriptación
CREATE EXTENSION IF NOT EXISTS "pgcrypto" SCHEMA public;

-- ============================================================
-- 1. TABLA: users (Usuarios del sistema)
-- ============================================================
CREATE TABLE public.users (
    pk_users                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   varchar(255) NOT NULL DEFAULT '',
    password_hash           varchar(255) NOT NULL DEFAULT '',
    first_name              varchar(100) NOT NULL DEFAULT '',
    last_name               varchar(100) NOT NULL DEFAULT '',
    phone                   varchar(20) NOT NULL DEFAULT '',
    is_email_verified       boolean NOT NULL DEFAULT false,
    email_verification_token varchar(255) NOT NULL DEFAULT '',
    password_reset_token    varchar(255) NOT NULL DEFAULT '',
    password_reset_expires  timestamp without time zone,
    is_active               boolean NOT NULL DEFAULT true,
    has_consent_privacy     boolean NOT NULL DEFAULT false,
    consent_date            timestamp without time zone,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_email UNIQUE (email)
);

COMMENT ON TABLE public.users IS 'Usuarios registrados en la plataforma Eternum';

-- Índices para users
CREATE INDEX idx_users_email ON public.users(email);
CREATE INDEX idx_users_active ON public.users(is_active);

-- ============================================================
-- 2. TABLA: memorial (Memoriales de fallecidos)
-- ============================================================
CREATE TABLE public.memorial (
    pk_memorial             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user                 integer NOT NULL,
    deceased_name           varchar(200) NOT NULL DEFAULT '',
    deceased_last_name      varchar(200) NOT NULL DEFAULT '',
    birth_date              date,
    death_date              date NOT NULL,
    biography               text NOT NULL DEFAULT '',
    epitaph                 varchar(500) NOT NULL DEFAULT '',
    profile_photo_url       varchar(500) NOT NULL DEFAULT '',
    is_featured             boolean NOT NULL DEFAULT false,
    candle_count            integer NOT NULL DEFAULT 0,
    is_active               boolean NOT NULL DEFAULT true,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_memorial_user FOREIGN KEY (fk_user)
        REFERENCES public.users(pk_users) ON DELETE CASCADE
);

COMMENT ON TABLE public.memorial IS 'Perfiles de memoriales para recordar a seres queridos fallecidos';

-- Índices para memorial
CREATE INDEX idx_memorial_user ON public.memorial(fk_user);
CREATE INDEX idx_memorial_dates ON public.memorial(death_date, birth_date);
CREATE INDEX idx_memorial_featured ON public.memorial(is_featured) WHERE is_featured = true;
CREATE INDEX idx_memorial_active ON public.memorial(is_active);

-- ============================================================
-- 3. TABLA: memorial_photo (Galería de fotos por memorial)
-- ============================================================
CREATE TABLE public.memorial_photo (
    pk_memorial_photo       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_memorial             integer NOT NULL,
    photo_url               varchar(500) NOT NULL DEFAULT '',
    caption                 varchar(255) NOT NULL DEFAULT '',
    display_order           integer NOT NULL DEFAULT 0,
    is_main_photo           boolean NOT NULL DEFAULT false,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_memorial_photo_memorial FOREIGN KEY (fk_memorial)
        REFERENCES public.memorial(pk_memorial) ON DELETE CASCADE
);

COMMENT ON TABLE public.memorial_photo IS 'Fotos y multimedia asociadas a cada memorial';

-- Índices para memorial_photo
CREATE INDEX idx_photo_memorial ON public.memorial_photo(fk_memorial);
CREATE INDEX idx_photo_main ON public.memorial_photo(is_main_photo) WHERE is_main_photo = true;

-- ============================================================
-- 4. TABLA: deactivation_request (Solicitudes de desactivación)
-- ============================================================
CREATE TABLE public.deactivation_request (
    pk_deactivation_request integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_requester_user       integer NOT NULL,
    deceased_full_name      varchar(400) NOT NULL DEFAULT '',
    deceased_email          varchar(255) NOT NULL DEFAULT '',
    social_media_platform   varchar(100) NOT NULL DEFAULT '',
    social_media_username   varchar(200) NOT NULL DEFAULT '',
    proof_document_url      varchar(500) NOT NULL DEFAULT '',
    death_certificate_url   varchar(500) NOT NULL DEFAULT '',
    request_status          varchar(50) NOT NULL DEFAULT 'PENDING',
    status_notes            text NOT NULL DEFAULT '',
    submitted_date          timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_date          timestamp without time zone,
    processed_by            integer NOT NULL DEFAULT 0,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_deactivation_requester FOREIGN KEY (fk_requester_user)
        REFERENCES public.users(pk_users) ON DELETE CASCADE,
    CONSTRAINT chk_request_status CHECK (request_status IN ('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED'))
);

COMMENT ON TABLE public.deactivation_request IS 'Solicitudes para desactivar cuentas de redes sociales de fallecidos';

-- Índices para deactivation_request
CREATE INDEX idx_deactivation_requester ON public.deactivation_request(fk_requester_user);
CREATE INDEX idx_deactivation_status ON public.deactivation_request(request_status);

-- ============================================================
-- 5. TABLA: subscription (Suscripciones de usuarios)
-- ============================================================
CREATE TABLE public.subscription (
    pk_subscription         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user                 integer NOT NULL,
    plan_type               varchar(50) NOT NULL DEFAULT 'FREE',
    plan_name               varchar(100) NOT NULL DEFAULT '',
    monthly_price           numeric(16,2) NOT NULL DEFAULT 0,
    start_date              date NOT NULL DEFAULT CURRENT_DATE,
    end_date                date,
    is_active               boolean NOT NULL DEFAULT true,
    auto_renew              boolean NOT NULL DEFAULT false,
    payment_method          varchar(50) NOT NULL DEFAULT '',
    external_subscription_id varchar(255) NOT NULL DEFAULT '',
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_subscription_user FOREIGN KEY (fk_user)
        REFERENCES public.users(pk_users) ON DELETE CASCADE,
    CONSTRAINT chk_plan_type CHECK (plan_type IN ('FREE', 'BASIC', 'PREMIUM', 'FAMILY'))
);

COMMENT ON TABLE public.subscription IS 'Suscripciones de usuarios para funcionalidades premium';

-- Índices para subscription
CREATE INDEX idx_subscription_user ON public.subscription(fk_user);
CREATE INDEX idx_subscription_active ON public.subscription(is_active);

-- ============================================================
-- 6. TABLA: payment_transaction (Transacciones de pago)
-- ============================================================
CREATE TABLE public.payment_transaction (
    pk_payment_transaction  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_subscription         integer NOT NULL,
    fk_user                 integer NOT NULL,
    amount                  numeric(16,2) NOT NULL DEFAULT 0,
    currency                varchar(3) NOT NULL DEFAULT 'USD',
    transaction_type        varchar(50) NOT NULL DEFAULT 'SUBSCRIPTION',
    payment_status          varchar(50) NOT NULL DEFAULT 'PENDING',
    payment_method          varchar(50) NOT NULL DEFAULT '',
    external_transaction_id varchar(255) NOT NULL DEFAULT '',
    payment_gateway_response text NOT NULL DEFAULT '',
    processed_date          timestamp without time zone,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_payment_subscription FOREIGN KEY (fk_subscription)
        REFERENCES public.subscription(pk_subscription) ON DELETE CASCADE,
    CONSTRAINT fk_payment_user FOREIGN KEY (fk_user)
        REFERENCES public.users(pk_users) ON DELETE CASCADE,
    CONSTRAINT chk_payment_status CHECK (payment_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED'))
);

COMMENT ON TABLE public.payment_transaction IS 'Registro de transacciones de pago de suscripciones';

-- Índices para payment_transaction
CREATE INDEX idx_payment_subscription ON public.payment_transaction(fk_subscription);
CREATE INDEX idx_payment_user ON public.payment_transaction(fk_user);
CREATE INDEX idx_payment_status ON public.payment_transaction(payment_status);

-- ============================================================
-- 7. TABLA: condolence (Condolencias en memoriales)
-- ============================================================
CREATE TABLE public.condolence (
    pk_condolence           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_memorial             integer NOT NULL,
    fk_author_user          integer,
    author_name             varchar(200) NOT NULL DEFAULT '',
    author_email            varchar(255) NOT NULL DEFAULT '',
    message                 text NOT NULL DEFAULT '',
    is_approved             boolean NOT NULL DEFAULT true,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_condolence_memorial FOREIGN KEY (fk_memorial)
        REFERENCES public.memorial(pk_memorial) ON DELETE CASCADE,
    CONSTRAINT fk_condolence_author FOREIGN KEY (fk_author_user)
        REFERENCES public.users(pk_users) ON DELETE SET NULL
);

COMMENT ON TABLE public.condolence IS 'Mensajes de condolencia y recuerdos en memoriales';

-- Índices para condolence
CREATE INDEX idx_condolence_memorial ON public.condolence(fk_memorial);
CREATE INDEX idx_condolence_author ON public.condolence(fk_author_user);

-- ============================================================
-- 8. TABLA: virtual_candle (Velas virtuales encendidas)
-- ============================================================
CREATE TABLE public.virtual_candle (
    pk_virtual_candle       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_memorial             integer NOT NULL,
    fk_user                 integer,
    candle_message          varchar(255) NOT NULL DEFAULT '',
    lit_date                timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_candle_memorial FOREIGN KEY (fk_memorial)
        REFERENCES public.memorial(pk_memorial) ON DELETE CASCADE,
    CONSTRAINT fk_candle_user FOREIGN KEY (fk_user)
        REFERENCES public.users(pk_users) ON DELETE SET NULL
);

COMMENT ON TABLE public.virtual_candle IS 'Registro de velas virtuales encendidas en memoriales';

-- Índices para virtual_candle
CREATE INDEX idx_candle_memorial ON public.virtual_candle(fk_memorial);
CREATE INDEX idx_candle_user ON public.virtual_candle(fk_user);

-- ============================================================
-- 9. TABLA: notification (Notificaciones del sistema)
-- ============================================================
CREATE TABLE public.notification (
    pk_notification         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user                 integer NOT NULL,
    notification_type       varchar(50) NOT NULL DEFAULT '',
    title                   varchar(200) NOT NULL DEFAULT '',
    message                 text NOT NULL DEFAULT '',
    related_entity_type     varchar(50) NOT NULL DEFAULT '',
    related_entity_id       integer NOT NULL DEFAULT 0,
    is_read                 boolean NOT NULL DEFAULT false,
    read_date               timestamp without time zone,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_notification_user FOREIGN KEY (fk_user)
        REFERENCES public.users(pk_users) ON DELETE CASCADE,
    CONSTRAINT chk_notification_type CHECK (notification_type IN ('ANNIVERSARY', 'CANDLE_LIT', 'CONDOLENCE_RECEIVED', 'SYSTEM', 'PAYMENT', 'REQUEST_UPDATE'))
);

COMMENT ON TABLE public.notification IS 'Notificaciones enviadas a usuarios';

-- Índices para notification
CREATE INDEX idx_notification_user ON public.notification(fk_user);
CREATE INDEX idx_notification_unread ON public.notification(is_read) WHERE is_read = false;

-- ============================================================
-- 10. TABLA: social_media_search (Búsquedas en redes sociales)
-- ============================================================
CREATE TABLE public.social_media_search (
    pk_social_media_search  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user                 integer NOT NULL,
    search_query            varchar(400) NOT NULL DEFAULT '',
    platform_searched       varchar(100) NOT NULL DEFAULT '',
    search_results_json     jsonb NOT NULL DEFAULT '{}',
    results_count           integer NOT NULL DEFAULT 0,
    search_date             timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              integer NOT NULL DEFAULT 0,
    updated_by              integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_search_user FOREIGN KEY (fk_user)
        REFERENCES public.users(pk_users) ON DELETE CASCADE
);

COMMENT ON TABLE public.social_media_search IS 'Historial de búsquedas de cuentas en redes sociales';

-- Índices para social_media_search
CREATE INDEX idx_search_user ON public.social_media_search(fk_user);
CREATE INDEX idx_search_platform ON public.social_media_search(platform_searched);

-- ============================================================
-- FUNCIONES AUXILIARES
-- ============================================================

-- Función para generar UUID en mayúsculas
CREATE OR REPLACE FUNCTION public.generate_uppercase_uuid()
RETURNS varchar(36) AS $$
BEGIN
    RETURN UPPER(gen_random_uuid()::varchar(36));
END;
$$ LANGUAGE plpgsql;

-- Función para formatear número de secuencia de 15 dígitos
CREATE OR REPLACE FUNCTION public.formatear_numero_secuencia(p_numero integer)
RETURNS varchar(15) AS $$
BEGIN
    RETURN LPAD(p_numero::varchar, 15, '0');
END;
$$ LANGUAGE plpgsql;

-- Función para actualizar updated_date automáticamente
CREATE OR REPLACE FUNCTION public.update_updated_date_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- TRIGGERS para actualizar updated_date automáticamente
-- ============================================================
CREATE TRIGGER trg_users_updated_date BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_memorial_updated_date BEFORE UPDATE ON public.memorial
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_memorial_photo_updated_date BEFORE UPDATE ON public.memorial_photo
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_deactivation_request_updated_date BEFORE UPDATE ON public.deactivation_request
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_subscription_updated_date BEFORE UPDATE ON public.subscription
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_payment_transaction_updated_date BEFORE UPDATE ON public.payment_transaction
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_condolence_updated_date BEFORE UPDATE ON public.condolence
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_virtual_candle_updated_date BEFORE UPDATE ON public.virtual_candle
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_notification_updated_date BEFORE UPDATE ON public.notification
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

CREATE TRIGGER trg_social_media_search_updated_date BEFORE UPDATE ON public.social_media_search
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_date_column();

-- ============================================================
-- DATOS INICIALES (Opcional)
-- ============================================================

-- Insertar usuario administrador de prueba (password: admin123)
-- La contraseña debe ser hasheada con BCrypt en la aplicación
-- INSERT INTO public.users (email, password_hash, first_name, last_name, is_email_verified, is_active)
-- VALUES ('admin@eternum.com', '$2a$10$...hash...', 'Admin', 'Eternum', true, true);
